//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace npva.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MovingAverageByLeft {
            get {
                return ((bool)(this["MovingAverageByLeft"]));
            }
            set {
                this["MovingAverageByLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartupAuthor {
            get {
                return ((string)(this["StartupAuthor"]));
            }
            set {
                this["StartupAuthor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AuthorSummaryPvLength {
            get {
                return ((int)(this["AuthorSummaryPvLength"]));
            }
            set {
                this["AuthorSummaryPvLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCIgnoreTotalPv {
            get {
                return ((bool)(this["CCIgnoreTotalPv"]));
            }
            set {
                this["CCIgnoreTotalPv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCIgnoreDailyPv {
            get {
                return ((bool)(this["CCIgnoreDailyPv"]));
            }
            set {
                this["CCIgnoreDailyPv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCIgnoreMovingAverage {
            get {
                return ((bool)(this["CCIgnoreMovingAverage"]));
            }
            set {
                this["CCIgnoreMovingAverage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCIgnoreBacklog7 {
            get {
                return ((bool)(this["CCIgnoreBacklog7"]));
            }
            set {
                this["CCIgnoreBacklog7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCIgnoreBacklog30 {
            get {
                return ((bool)(this["CCIgnoreBacklog30"]));
            }
            set {
                this["CCIgnoreBacklog30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCIgnoreBacklog90 {
            get {
                return ((bool)(this["CCIgnoreBacklog90"]));
            }
            set {
                this["CCIgnoreBacklog90"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCIgnoreBacklog180 {
            get {
                return ((bool)(this["CCIgnoreBacklog180"]));
            }
            set {
                this["CCIgnoreBacklog180"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCIgnoreBacklog365 {
            get {
                return ((bool)(this["CCIgnoreBacklog365"]));
            }
            set {
                this["CCIgnoreBacklog365"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCIgnoreAllTime {
            get {
                return ((bool)(this["CCIgnoreAllTime"]));
            }
            set {
                this["CCIgnoreAllTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AnalizerGetPartialPV {
            get {
                return ((bool)(this["AnalizerGetPartialPV"]));
            }
            set {
                this["AnalizerGetPartialPV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChartExcludePV {
            get {
                return ((bool)(this["ChartExcludePV"]));
            }
            set {
                this["ChartExcludePV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChartExcludeUnique {
            get {
                return ((bool)(this["ChartExcludeUnique"]));
            }
            set {
                this["ChartExcludeUnique"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChartExcludeScore {
            get {
                return ((bool)(this["ChartExcludeScore"]));
            }
            set {
                this["ChartExcludeScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChartSaveAsIs {
            get {
                return ((bool)(this["ChartSaveAsIs"]));
            }
            set {
                this["ChartSaveAsIs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public int ChartSaveWidth {
            get {
                return ((int)(this["ChartSaveWidth"]));
            }
            set {
                this["ChartSaveWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public int ChartSaveHeight {
            get {
                return ((int)(this["ChartSaveHeight"]));
            }
            set {
                this["ChartSaveHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PPVWeekFromMonday {
            get {
                return ((bool)(this["PPVWeekFromMonday"]));
            }
            set {
                this["PPVWeekFromMonday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int PPVDays {
            get {
                return ((int)(this["PPVDays"]));
            }
            set {
                this["PPVDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CCIncludeUserRange {
            get {
                return ((bool)(this["CCIncludeUserRange"]));
            }
            set {
                this["CCIncludeUserRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int CCUserRange {
            get {
                return ((int)(this["CCUserRange"]));
            }
            set {
                this["CCUserRange"] = value;
            }
        }
    }
}
